# Nome da sua GitHub Action
name: Generate Snake

# Define quando a ação vai rodar
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# ADICIONAMOS ESTA SEÇÃO DE PERMISSÕES
permissions:
  contents: write

# Define o trabalho que será feito
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.svg?palette=ocean

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
