# Nome da sua GitHub Action
name: Generate Snake

# Define quando a ação vai rodar
on:
  # Roda a cada 6 horas automaticamente
  schedule:
    - cron: "0 */6 * * *"
  # Permite que você rode a ação manualmente pela aba "Actions"
  workflow_dispatch:

# Define o trabalho que será feito
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pega uma cópia do seu repositório para a ação poder trabalhar
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.svg?palette=ocean

      # Empurra a imagem gerada para uma branch chamada 'output'
      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
